on:
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: rapid-prototype
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: 'actions/checkout@v3'
      
      - id: 'setup-gcloud'
        name: 'Setup Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ secrets.WORKLOAD_IDENTITY_POOL_PROVIDER_ID }}'
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      
      - id: 'verify-auth'
        name: 'Verify Authentication'
        run: |
          echo "Verifying authentication..."
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud auth list
          gcloud projects describe ${{ secrets.PROJECT_ID }}